test: add infrastructure test (#9)
* test: separate stdout and stderr from printout infrastructure

* test: add test

* test: add git test

* test: add file test

* test: add deps test

* test: add config test

* test: add check is installed to deps test

* chore: add gofumpt

* test: add brew test

* fix: path is args

* test: fix mock data

* test: fix SetHomebrewEnv arg

* test: fix brew test

* fix: add stdout to BrewInfrastructure.InstallFormula

* test: disable parallel test

* feat: add brew tap and mas command

* test: install tap Homebrew/bundle

* test: rm mas test

* test: add Homebrew Install test

* ci: add cov test

* ci: add comment

* test: cover test

* ci: fix test ci

* test: cov test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,7 +6,7 @@ on:
       - "main"
 
 permissions:
-  contents: read
+  contents: write
   pull-requests: write
 
 jobs:
@@ -136,14 +136,20 @@ jobs:
     defaults:
       run:
         working-directory: scripts/dofy
+    env:
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}/cov
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/setup-golang
       - name: Run go test
         id: golang-test
         run: |
-          TEST_OUT=$(go test ./... -coverpkg=./... -p=5)
+          set +e
+          TEST_OUT=$(go test ./... -coverpkg=./... -coverprofile=cover.out -p=5)
           TEST_EXIT_CODE=$?
+          if [ $TEST_EXIT_CODE -eq 0 ]; then
+            go tool cover -html=cover.out -o index.html
+          fi
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           {
             echo "comment<<$EOF"
@@ -166,13 +172,58 @@ jobs:
           } >> "$GITHUB_ENV"
           exit $TEST_EXIT_CODE
         continue-on-error: true
+      - uses: actions/upload-artifact@v4
+        if: ${{ steps.golang-test.outcome == 'success' }}
+        with:
+          name: cov html
+          path: ${{ github.workspace }}/scripts/dofy/index.html
+          if-no-files-found: error
+      - uses: actions/checkout@v4
+        if: ${{ steps.golang-test.outcome == 'success' }}
+        with:
+          ref: github-pages
+          clean: false
+      - name: Set Git User
+        if: ${{ steps.golang-test.outcome == 'success' }}
+        working-directory: .
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      - name: Push HTML Report
+        if: ${{ steps.golang-test.outcome == 'success' }}
+        timeout-minutes: 3
+        working-directory: .
+        run: |
+          mkdir -p ${{ env.HTML_REPORT_URL_PATH }}
+          mv ./scripts/dofy/index.html ${{ env.HTML_REPORT_URL_PATH }}/index.html
+          
+          git add ${{ env.HTML_REPORT_URL_PATH }}
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+
+          while true; do
+            if ! git pull --rebase; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+
+            if git push; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+      - uses: actions/checkout@v4
+        if: ${{ steps.golang-test.outcome == 'success' }}
       - name: Create PR comment
         uses: marocchino/sticky-pull-request-comment@44e0bad81007ecff41ba26d1cbf49a0267d28e9d # v2.9.0
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           number: ${{ github.event.pull_request.number }}
           header: golang-test
-          message: ${{ env.comment }}
+          message: | 
+            ${{ env.comment }}
+
+            ## Cov HTML ${{ github.run_id }}: ${{ github.run_attempt }}
+            [Cov HTML Report](https://shiron-dev.github.io/dotfiles/${{ env.HTML_REPORT_URL_PATH }})
       - name: Error check
         if: ${{ steps.golang-test.outcome != 'success' }}
         run: exit 1
@@ -193,6 +244,7 @@ jobs:
       - name: Run go test
         id: golang-test
         run: |
+          set +e
           TEST_OUT=$(go test -json -v ./... -p=5 2>&1)
           TEST_EXIT=$?
           echo "$TEST_OUT" | tee /tmp/gotest.log | gotestfmt
